### ISSUE TITLE
当 rightStyle="iconSwitch"点击事件无效

### ISSUE THREAD

**Issue by adymilk** [leonHua/LSettingView#11]
当 rightStyle="iconSwitch"点击事件无效，大神。请问这是什么原因？

**Comment by leonHua** [comment]
额，我这里运行是OK的，描述下具体的版本环境，另外可以把把示例代码跑一下看看效果有没有。

**Comment by kentlee2** [comment]
我的也是一样，点击事件也是无效，是什么原因呢

**Comment by adymilk** [comment]
换成 iconShow 就可以了

**Comment by adymilk** [comment]
@leonHua 实例代码里也是这样情况。点击事件只能 响应 switch 的True或是False.。无法响应当前点击Item的点击事件。

**Comment by adymilk** [comment]
@kentlee2 [详情可参照我这个](https://github.com/adymilk/xinBrowser/blob/master/app/src/main/java/com/adymilk/easybrowser/por/SetttingActivity.java)

**Comment by leonHua** [comment]
@adymilk @kentlee2 问题已经修复，使用最新版本1.6.0即可，有问题欢迎继续反馈哈
