### ISSUE TITLE
设置rightIcon为hide

### ISSUE THREAD

**Issue by guoq1** [leonHua/LSettingView#13]
设置右侧文字会显示靠左, 右侧图片为invisible
在源码
case 1:
                //隐藏右侧图标
                mRightLayout.setVisibility(View.INVISIBLE);
                mRightLayout.getLayoutParams().width = 32;//多加一行这个将文字设置靠右对齐即可
                break;

**Comment by leonHua** [comment]
这个是什么系统上遇到的问题，我试了下没发现这个问题？

**Comment by guoq1** [comment]
比如设置右侧为只有文字的时候,不显示右箭头

**Comment by leonHua** [comment]
[https://github.com/leonHua/LSettingView/blob/master/screenshot/Screenshot_2018-01-18-11-22-36.png](url)我设置了右侧只有文字，不显示箭头，貌似没发现问题，你看看和你的效果一样不？可以传个图看你的效果是什么样的？

**Comment by leonHua** [comment]
点击好像看不了，就在本项目下的screenshot文件夹下，名称Screenshot_2018-01-18-11-22-36.png，你看看

**Comment by guoq1** [comment]
恩看了,就比如 "我的下载" 这行 "v1.0" 一般是要对齐到右侧,和分割线右边一样,现在显示右侧空开整体不太好看

**Comment by leonHua** [comment]
明白你说的意思了，确实是，代码已经改了，不过这个改动太小了，等到下一个版本在同一发版吧。如果你对这个有硬性要求，就把下载代码使用吧先~~
