### ISSUE TITLE
Couldn't resolve resource @id/iv_lefticon

### ISSUE THREAD

**Issue by walker8** [leonHua/LSettingView#4]
这个怎么解决？

**Comment by leonHua** [comment]
这个看不出来问题啊，能把你的整个布局贴出来吗？

**Comment by walker8** [comment]
应该不是布局问题，我用android studio2.3.2新建了一个工程，然后添加依赖，在布局里加入LSettingItem就提示这个问题，网上说重启可以解决，我重启了也没效果
[图1](http://wx1.sinaimg.cn/large/ae13467dgy1fhphaks4gpj20go0h8wgi.jpg)
[图2](http://wx3.sinaimg.cn/large/ae13467dgy1fhphal1iz2j20cm0j3wfl.jpg)
@leonHua

**Comment by leonHua** [comment]
这个是预览的警告，你运行下应该可以的，运行报错吗@walker8

**Comment by walker8** [comment]
运行倒还真不报错，但总觉得怪怪的，而且我下载你的demo，用Android Studio打开也没这个问题

**Comment by qaz349293703** [comment]
我也有这个问题。然后在AS上预览布局效果的时候，左侧的图标和左侧的文字是重叠在一起的。
