### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by xuelangren** [leonHua/LSettingView#5]
下边的那个开关按钮和checkbox 不是太智能，一般如果能打开关闭都会去对开关状态做一个监听的！希望楼主能改进，我水平太差，无能为力！静待楼主

**Comment by leonHua** [comment]
最近有点忙，等有时间了会把这些在完善一下，继续关注哈

**Comment by leonHua** [comment]
@xuelangren 已经更新版本， 增加了对状态的监听，谢谢反馈意见
