### ISSUE TITLE
请问怎么设置右侧文字？

### ISSUE THREAD

**Issue by ufotree2017** [leonHua/LSettingView#6]
请问怎么设置右侧文字？

**Comment by leonHua** [comment]
rightText | 右侧文字 
rightTextSize | 右侧文字大小 
rightTextColor|颜色
这几个属性呀，目前版本只有在XML中配置，下一版本会增加在代码中动态设置接口，谢谢

**Comment by leonHua** [comment]
@ufotree2017 已经更新了版本，可以更改文字，关联最新版本后可以使用

**Comment by ufotree2017** [comment]
好的，谢谢
