### ISSUE TITLE
设置右侧文字的问题

### ISSUE THREAD

**Issue by ufotree2017** [leonHua/LSettingView#7]
你好，反馈一个问题，代码中设置右侧文字之后有时候文字会竖起来显示，刷新后又正常了。
比如设置文字为100，可能会显示成     
 1
                                                               0
                                                               0

**Comment by leonHua** [comment]
我这里测试了下，只有在右侧文字过长的情况下回换行，但是右侧文字应该都不会过长吧。看你的描述，刷新后又正常了，我没复现现这个问题不好排查啊，还有更多的信息可提供吗

**Comment by ufotree2017** [comment]
你好，我测试了一下，是在线程里循环对Lsettingview设置右侧的文字才会出现这个问题，是我的用法有问题。
