### ISSUE TITLE
左侧不设icon出现的问题

### ISSUE THREAD

**Issue by qaz349293703** [leonHua/LSettingView#8]
左侧没有设置icon。为什么默认出来一个爱心图标？？这样有问题吧。

**Comment by qaz349293703** [comment]
而且右侧或者左侧的icon如果不设置。这个icon相应所占的控件的宽度应该没有了。但是因为你ImageView都写死了24dp,所以如果不设置icon,左侧或者右侧还是会空出来一块。

**Comment by qaz349293703** [comment]
还有就是设置左边的文字大小用float，右边文字大小又用dimen类型，最好统一下

**Comment by leonHua** [comment]
@qaz349293703 左侧图片默认去掉不显示。左右大小都使用float
