### ISSUE TITLE
style里面textSize可以换个名字么

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [leonHua/LSettingView#9]
textSize和textColor与原来别的style重复了，所以建议在style中textSize和textColor能换一个不会重复的名字来命名，不然去改别的地方容易乱，辛苦楼主

**Comment by leonHua** [comment]
@zhongzhihuashanghai 这个问题疏忽了，确实会很可能碰到，我这周更新这个问题，谢谢

**Comment by leonHua** [comment]
@zhongzhihuashanghai 属性名称已经更新为 LtextSize 和 LtextColor ，最新版本为1.5.0，有问题在提给我，谢谢
